package:
  name: link-grammar-minisat-bundled
  version: "5.6.2"

source:
  url: https://www.abisource.com/downloads/link-grammar/5.6.2/link-grammar-5.6.2.tar.gz

build:
  number: 3
  string: py37_3

requirements:
  host:
    - python==3.7

  build:
#    - make
#    - m4
#    - gcc
#    - autoconf
##    - autoconf-archive
#    - pkg-config
#    - flex
#    - ant
#    - graphviz
  run:
    -  libgcc
#    -  geos
#    -  proj4
#    -  json-c
#    -  libxml2
#    -  postgresql >=9.1

about:
  home: https://www.abisource.com/projects/link-grammar/
  license: GPL2
